export const SEARCH_STOCK = 'SEARCH_STOCK';
export const SEARCH_STOCK_SUCCESS = 'SEARCH_STOCK_SUCCESS';
export const SEARCH_STOCK_FAILURE = 'SEARCH_STOCK_FAILURE';

export const CLEAR_STOCK = 'CLEAR_STOCK';
